# Generated by Django 2.1.7 on 2019-02-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.TextField(unique=True)),
                ('detail_url', models.TextField(blank=True, null=True)),
                ('raw_title', models.TextField(blank=True, null=True)),
                ('view_price', models.TextField(blank=True, null=True)),
                ('view_fee', models.TextField(blank=True, null=True)),
                ('item_loc', models.TextField(blank=True, null=True)),
                ('view_sales', models.TextField(blank=True, null=True)),
                ('comment_count', models.TextField(blank=True, null=True)),
                ('nick', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'datas',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='ManageInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.TextField(blank=True, null=True)),
                ('manager_password', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'manage_information',
            },
        ),
        migrations.CreateModel(
            name='MenunameInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuname', models.TextField(blank=True, null=True)),
                ('cuisine_field', models.TextField(blank=True, db_column='Cuisine ', null=True)),
                ('introduce_field', models.TextField(blank=True, db_column='introduce ', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'menuname_information',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(blank=True, null=True)),
                ('anser1', models.TextField(blank=True, null=True)),
                ('anser2', models.TextField(blank=True, null=True)),
                ('anser3', models.TextField(blank=True, null=True)),
                ('anser4', models.TextField(blank=True, null=True)),
                ('anser5', models.TextField(blank=True, null=True)),
                ('anser6', models.TextField(blank=True, null=True)),
                ('anser7', models.TextField(blank=True, null=True)),
                ('anser8', models.TextField(blank=True, null=True)),
                ('anser9', models.TextField(blank=True, null=True)),
                ('anser10', models.TextField(blank=True, null=True)),
                ('anser11', models.TextField(blank=True, null=True)),
                ('anser12', models.TextField(blank=True, null=True)),
                ('anser13', models.TextField(blank=True, null=True)),
                ('anser14', models.TextField(blank=True, null=True)),
                ('anser15', models.TextField(blank=True, null=True)),
                ('anser16', models.TextField(blank=True, null=True)),
                ('anser17', models.TextField(blank=True, null=True)),
                ('anser18', models.TextField(blank=True, null=True)),
                ('anser19', models.TextField(blank=True, null=True)),
                ('anser20', models.TextField(blank=True, null=True)),
                ('anser21', models.TextField(blank=True, null=True)),
                ('anser22', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='RecongnizeUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
            options={
                'managed': False,
                'db_table': 'recongnize_user',
            },
        ),
        migrations.CreateModel(
            name='BannerIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名字')),
                ('index_image', models.ImageField(blank=True, upload_to='products_images/%Y%m%d', verbose_name='banner图')),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(blank=True, null=True)),
                ('the_most_nice', models.TextField(blank=True, null=True)),
                ('the_demost_dence', models.TextField(blank=True, null=True)),
                ('all_motion', models.TextField(blank=True, null=True)),
                ('wishes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='SelectMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='已选菜单')),
                ('user', models.CharField(max_length=120, verbose_name='选择人')),
            ],
            options={
                'db_table': 'selectmenu',
            },
        ),
    ]
