# Generated by Django 2.1.7 on 2019-02-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
