# Generated by Django 2.1.7 on 2019-02-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_one', '0002_request_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
