# Generated by Django 2.1.7 on 2019-02-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_one', '0003_auto_20190223_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
