# Generated by Django 2.1.7 on 2019-02-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_one', '0004_question_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectmenu',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
